import { Constellation, SkillNode, WoodMaterial, PaintFinish } from './types';

export const CONSTELLATIONS: Constellation[] = [
  {
    id: 'cup',
    name: 'Cup',
    chineseName: '杯技',
    element: 'fire',
    description: '大皿·小皿·中皿，剑玉启航之本。',
    themeColor: '#C77D7A',
  },
  {
    id: 'balance',
    name: 'Balance',
    chineseName: '平衡系',
    element: 'water',
    description: '极意·鸟渡·安德鸟，静态定力之巅。',
    themeColor: '#5EADAC',
  },
  {
    id: 'airplane',
    name: 'Airplane',
    chineseName: '飞机系',
    element: 'air',
    description: '跳剑·UFO·回转飞机，凌空飞转。',
    themeColor: '#7AAE93',
  },
  {
    id: 'downspike',
    name: 'Downspike',
    chineseName: '地狱车',
    element: 'fire',
    description: '天中杀·玉中杀·地狱车，深渊刺击。',
    themeColor: '#C4697A',
  },
  {
    id: 'lunar',
    name: 'Lunar',
    chineseName: '月面系',
    element: 'water',
    description: '月面·逆月·梦月，潮汐流转之衡。',
    themeColor: '#8B83D6',
  },
  {
    id: 'gunslinger',
    name: 'Gunslinger',
    chineseName: '神枪手',
    element: 'fire',
    description: '神枪手地球·转剑·天中杀，一击必中。',
    themeColor: '#A989CF',
  },
  {
    id: 'juggle',
    name: 'Juggle',
    chineseName: '小丑',
    element: 'air',
    description: '小丑止剑1-10，层层递进之艺。',
    themeColor: '#D491A8',
  },
  {
    id: 'kenflip',
    name: 'Kenflip',
    chineseName: '离转系',
    element: 'earth',
    description: '离转地球·正反离转，翻转之精控。',
    themeColor: '#7D8AC9',
  },
  {
    id: 'lighthouse',
    name: 'Lighthouse',
    chineseName: '灯台系',
    element: 'earth',
    description: '灯台·回转灯台·幽灵灯台，柄上星河。',
    themeColor: '#C99B5B',
  },
  {
    id: 'stilt',
    name: 'Stilt',
    chineseName: '竹马战斧',
    element: 'air',
    description: '战斧·竹马·钩子，力巧之交锋。',
    themeColor: '#98B56C',
  },
  {
    id: 'string',
    name: 'String',
    chineseName: '线技',
    element: 'water',
    description: '提线止剑·飞行V·宇宙游泳，线织星舞。',
    themeColor: '#C9964A',
  },
  {
    id: 'tap',
    name: 'Tap',
    chineseName: '快手',
    element: 'earth',
    description: '1-4 Tap·快手系列，速与准之极。',
    themeColor: '#CF8A56',
  },
];

export const SKILL_NODES: SkillNode[] = [
  // ========== CUP (杯技) ==========
  { id: 'cup_1', title: '大皿', subTitle: 'Big Cup', constellationId: 'cup', category: 'cup', description: '基础入门招式，用剑玉的大杯接住球', difficulty: 1, unlockRequirements: [], x: 49, y: 79 },
  { id: 'cup_2', title: '小皿', subTitle: 'Small Cup', constellationId: 'cup', category: 'cup', description: '用小杯接球，精确度要求更高', difficulty: 1, unlockRequirements: ['cup_1'], x: 52, y: 70 },
  { id: 'cup_3', title: '中皿', subTitle: 'Base Cup', constellationId: 'cup', category: 'cup', description: '用底部的皿接球，平衡的关键', difficulty: 2, unlockRequirements: ['cup_2'], x: 48, y: 65 },
  { id: 'cup_4', title: '止剑', subTitle: 'Spike', constellationId: 'cup', category: 'cup', description: '用剑尖精准刺入球孔，瞬间停止', difficulty: 2, unlockRequirements: ['cup_3'], x: 54, y: 56 },
  { id: 'cup_5', title: '地球', subTitle: 'Earth Turn', constellationId: 'cup', category: 'cup', description: '球绕剑旋转一周，经典回转技', difficulty: 3, unlockRequirements: ['cup_4'], x: 65, y: 56 },
  { id: 'cup_6', title: '游泳', subTitle: 'Swing', constellationId: 'cup', category: 'cup', description: '绳间穿行的流线型动作', difficulty: 3, unlockRequirements: ['cup_4'], x: 35, y: 56 },
  { id: 'cup_7', title: '日本一周', subTitle: 'Japan One Turn', constellationId: 'cup', category: 'cup', description: '日式一周回转，经典连招核心', difficulty: 3, unlockRequirements: ['cup_4'], x: 47, y: 47 },
  { id: 'cup_8', title: '世界一周', subTitle: 'World One Turn', constellationId: 'cup', category: 'cup', description: '球与剑的完美配合，世界级一周', difficulty: 4, unlockRequirements: ['cup_7'], x: 53, y: 38 },
  { id: 'cup_9', title: '欧洲一周', subTitle: 'Europe One Turn', constellationId: 'cup', category: 'cup', description: '欧式一周，风格独特的回转技', difficulty: 4, unlockRequirements: ['cup_8'], x: 46, y: 29 },
  { id: 'cup_10', title: '美国一周', subTitle: 'USA One Turn', constellationId: 'cup', category: 'cup', description: '美式一周，高难度终极回转', difficulty: 5, unlockRequirements: ['cup_9'], x: 49, y: 17 },

  // ========== BALANCE (平衡系) ==========
  { id: 'balance_1', title: '太阳极意', subTitle: 'Solar Extreme', constellationId: 'balance', category: 'balance', description: '平衡系的起点，专注力如太阳般凝聚', difficulty: 2, unlockRequirements: [], x: 33, y: 25 },
  { id: 'balance_2', title: '中皿极意', subTitle: 'Base Cup Extreme', constellationId: 'balance', category: 'balance', description: '中皿上的极致平衡', difficulty: 2, unlockRequirements: ['balance_1'], x: 42, y: 37 },
  { id: 'balance_3', title: '极意一周', subTitle: 'Extreme One Turn', constellationId: 'balance', category: 'balance', description: '极意状态下的完美一周', difficulty: 3, unlockRequirements: ['balance_2'], x: 64, y: 33 },
  { id: 'balance_4', title: '鸟渡', subTitle: 'Bird Over Valley', constellationId: 'balance', category: 'balance', description: '如鸟般轻盈的过渡动作', difficulty: 3, unlockRequirements: ['balance_2'], x: 48, y: 55 },
  { id: 'balance_5', title: '安德鸟', subTitle: 'Ando Bird', constellationId: 'balance', category: 'balance', description: '安德风格的鸟系平衡技', difficulty: 3, unlockRequirements: ['balance_4'], x: 40, y: 48 },
  { id: 'balance_6', title: '安德鸟渡', subTitle: 'Ando Bird Transfer', constellationId: 'balance', category: 'balance', description: '安德鸟的转移变体', difficulty: 4, unlockRequirements: ['balance_5'], x: 19, y: 49 },
  { id: 'balance_7', title: '小鸟', subTitle: 'Small Bird', constellationId: 'balance', category: 'balance', description: '基础鸟系平衡入门', difficulty: 3, unlockRequirements: ['balance_4'], x: 47, y: 66 },
  { id: 'balance_8', title: '大鸟', subTitle: 'Big Bird', constellationId: 'balance', category: 'balance', description: '大型鸟系平衡，气势磅礴', difficulty: 4, unlockRequirements: ['balance_7'], x: 49, y: 75 },
  { id: 'balance_9', title: '大鸟1回转', subTitle: 'Big Bird 1 Turn', constellationId: 'balance', category: 'balance', description: '大鸟加一回转的复合技', difficulty: 4, unlockRequirements: ['balance_8'], x: 62, y: 46 },
  { id: 'balance_10', title: '银河一周', subTitle: 'Galaxy One Turn', constellationId: 'balance', category: 'balance', description: '如银河般壮丽的终极回转', difficulty: 5, unlockRequirements: ['balance_9'], x: 78, y: 53 },

  // ========== AIRPLANE (飞机系) ==========
  { id: 'airplane_1', title: '飞机', subTitle: 'Airplane', constellationId: 'airplane', category: 'airplane', description: '飞机系核心起手式，球与剑平行旋转', difficulty: 2, unlockRequirements: [], x: 50, y: 50 },
  { id: 'airplane_2', title: '1回转飞机', subTitle: '1-Turn Airplane', constellationId: 'airplane', category: 'airplane', description: '飞机加单回转', difficulty: 3, unlockRequirements: ['airplane_1'], x: 38, y: 58 },
  { id: 'airplane_3', title: '2回转飞机', subTitle: '2-Turn Airplane', constellationId: 'airplane', category: 'airplane', description: '飞机加双回转', difficulty: 3, unlockRequirements: ['airplane_2'], x: 33, y: 47 },
  { id: 'airplane_4', title: '3回转飞机', subTitle: '3-Turn Airplane', constellationId: 'airplane', category: 'airplane', description: '飞机加三回转，难度飙升', difficulty: 4, unlockRequirements: ['airplane_3'], x: 20, y: 47 },
  { id: 'airplane_5', title: 'UFO', subTitle: 'UFO', constellationId: 'airplane', category: 'airplane', description: '球如飞碟般悬浮旋转', difficulty: 3, unlockRequirements: ['airplane_1'], x: 46, y: 38 },
  { id: 'airplane_6', title: '跳剑1.5持剑收', subTitle: 'Jump 1.5 Ken Catch', constellationId: 'airplane', category: 'airplane', description: '跳剑1.5圈后持剑接住', difficulty: 4, unlockRequirements: ['airplane_5'], x: 50, y: 31 },
  { id: 'airplane_7', title: '跳剑', subTitle: 'Jumping Stick', constellationId: 'airplane', category: 'airplane', description: '基础跳剑，剑体翻转', difficulty: 2, unlockRequirements: ['airplane_1', 'airplane_6'], x: 64, y: 46 },
  { id: 'airplane_8', title: '跳剑2', subTitle: 'Jump Ken 2', constellationId: 'airplane', category: 'airplane', description: '跳剑两圈，双倍难度', difficulty: 4, unlockRequirements: ['airplane_7'], x: 65, y: 59 },
  { id: 'airplane_9', title: '跳剑3', subTitle: 'Jump Ken 3', constellationId: 'airplane', category: 'airplane', description: '跳剑三圈，高手境界', difficulty: 4, unlockRequirements: ['airplane_7'], x: 75, y: 51 },
  { id: 'airplane_10', title: '跳剑1-2-3', subTitle: 'Jump Ken 1-2-3', constellationId: 'airplane', category: 'airplane', description: '跳剑1到3连续递增，终极连招', difficulty: 5, unlockRequirements: ['airplane_9'], x: 82, y: 46 },

  // ========== DOWNSPIKE (地狱车) ==========
  { id: 'downspike_1', title: '天中杀', subTitle: 'Downspike', constellationId: 'downspike', category: 'downspike', description: '精准的向下刺击，地狱车起点', difficulty: 3, unlockRequirements: [], x: 50, y: 46 },
  { id: 'downspike_2', title: '皿上来回', subTitle: 'Cup Switch', constellationId: 'downspike', category: 'downspike', description: '皿间来回切换的基础动作', difficulty: 2, unlockRequirements: ['downspike_1'], x: 50, y: 22 },
  { id: 'downspike_3', title: '中皿天中杀', subTitle: 'Base Cup Heaven Spike', constellationId: 'downspike', category: 'downspike', description: '中皿起手接天中杀', difficulty: 3, unlockRequirements: ['downspike_1', 'downspike_2'], x: 53, y: 36 },
  { id: 'downspike_4', title: '天中杀一周', subTitle: 'Heaven Spike 1 Turn', constellationId: 'downspike', category: 'downspike', description: '天中杀加一回转', difficulty: 4, unlockRequirements: ['downspike_1'], x: 34, y: 46 },
  { id: 'downspike_5', title: '玉中杀', subTitle: 'Stuntplane', constellationId: 'downspike', category: 'downspike', description: '以球刺玉，反向技巧', difficulty: 3, unlockRequirements: ['downspike_1'], x: 65, y: 44 },
  { id: 'downspike_6', title: '玉中杀地狱车', subTitle: 'Ball Spike Hell Turn', constellationId: 'downspike', category: 'downspike', description: '玉中杀与地狱车的恐怖组合', difficulty: 4, unlockRequirements: ['downspike_1', 'downspike_5'], x: 59, y: 51 },
  { id: 'downspike_7', title: '天中杀地狱车', subTitle: 'Heaven Spike Hell Turn', constellationId: 'downspike', category: 'downspike', description: '天中杀直接接地狱车', difficulty: 4, unlockRequirements: ['downspike_1'], x: 46, y: 67 },
  { id: 'downspike_8', title: '天地二段', subTitle: 'Heaven-Earth Double', constellationId: 'downspike', category: 'downspike', description: '天与地的二段连续刺击', difficulty: 4, unlockRequirements: ['downspike_1'], x: 53, y: 61 },
  { id: 'downspike_9', title: '天地二段地狱车', subTitle: 'Heaven-Earth Hell Turn', constellationId: 'downspike', category: 'downspike', description: '天地二段连地狱车的三重杀', difficulty: 5, unlockRequirements: ['downspike_8', 'downspike_7'], x: 50, y: 80 },
  { id: 'downspike_10', title: '离转地狱车', subTitle: 'Kenflip Hell Turn', constellationId: 'downspike', category: 'downspike', description: '离转与地狱车的终极结合', difficulty: 5, unlockRequirements: ['downspike_9'], x: 50, y: 95 },

  // ========== LUNAR (月面系) ==========
  { id: 'lunar_1', title: '月面', subTitle: 'Lunar', constellationId: 'lunar', category: 'lunar', description: '月面系核心——球在剑皿边缘的精准平衡', difficulty: 2, unlockRequirements: [], x: 56, y: 82 },
  { id: 'lunar_2', title: '1回转月面', subTitle: '1-Turn Lunar', constellationId: 'lunar', category: 'lunar', description: '月面加一回转', difficulty: 3, unlockRequirements: ['lunar_1'], x: 24, y: 75 },
  { id: 'lunar_3', title: '月面360', subTitle: 'Lunar 360', constellationId: 'lunar', category: 'lunar', description: '月面360度大旋转', difficulty: 4, unlockRequirements: ['lunar_1'], x: 77, y: 67 },
  { id: 'lunar_4', title: '月上1回转', subTitle: 'Lunar 1 Turn Up', constellationId: 'lunar', category: 'lunar', description: '月面上方再加一回转', difficulty: 3, unlockRequirements: ['lunar_2'], x: 14, y: 56 },
  { id: 'lunar_5', title: '月上2回转', subTitle: 'Lunar 2 Turn Up', constellationId: 'lunar', category: 'lunar', description: '月面上方双回转', difficulty: 4, unlockRequirements: ['lunar_4'], x: 20, y: 32 },
  { id: 'lunar_6', title: '月面1-2-3', subTitle: 'Lunar 1-2-3', constellationId: 'lunar', category: 'lunar', description: '月面递增连招1到3', difficulty: 5, unlockRequirements: ['lunar_5'], x: 41, y: 17 },
  { id: 'lunar_7', title: '逆月', subTitle: 'Inward Lunar', constellationId: 'lunar', category: 'lunar', description: '反向月面平衡，难度翻倍', difficulty: 3, unlockRequirements: ['lunar_1'], x: 64, y: 50 },
  { id: 'lunar_8', title: '月面交错', subTitle: 'Lunar Cross', constellationId: 'lunar', category: 'lunar', description: '月面左右交替，节奏变换', difficulty: 4, unlockRequirements: ['lunar_1', 'lunar_7'], x: 57, y: 31 },
  { id: 'lunar_9', title: '月面大乱', subTitle: 'Lunar Chaos', constellationId: 'lunar', category: 'lunar', description: '月面乱序组合，不可预测', difficulty: 4, unlockRequirements: ['lunar_1'], x: 36, y: 44 },
  { id: 'lunar_10', title: '梦月', subTitle: 'Dream Lunar', constellationId: 'lunar', category: 'lunar', description: '如梦似幻的终极月面技', difficulty: 5, unlockRequirements: ['lunar_1', 'lunar_9'], x: 52, y: 61 },

  // ========== GUNSLINGER (神枪手) ==========
  { id: 'gunslinger_1', title: '神枪手大皿', subTitle: 'Gunslinger Big Cup', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手系列起点——大皿起手式', difficulty: 2, unlockRequirements: [], x: 85, y: 68 },
  { id: 'gunslinger_2', title: '神枪手止剑', subTitle: 'Gunslinger Spike', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手风格止剑', difficulty: 2, unlockRequirements: ['gunslinger_1'], x: 72, y: 62 },
  { id: 'gunslinger_3', title: '神枪手游泳', subTitle: 'Gunslinger Swimming', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手风格的绳间穿梭', difficulty: 3, unlockRequirements: ['gunslinger_2'], x: 66, y: 47 },
  { id: 'gunslinger_4', title: '神枪手地球', subTitle: 'Gunslinger Earth Turn', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手地球回转', difficulty: 3, unlockRequirements: ['gunslinger_3'], x: 55, y: 41 },
  { id: 'gunslinger_5', title: '神枪手游泳-神枪手地球', subTitle: 'Gunslinger Swim-Earth', constellationId: 'gunslinger', category: 'gunslinger', description: '游泳接地球的组合连招', difficulty: 4, unlockRequirements: ['gunslinger_4'], x: 70, y: 37 },
  { id: 'gunslinger_6', title: '2圈神枪手地球', subTitle: '2-Turn GS Earth', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手地球双圈', difficulty: 4, unlockRequirements: ['gunslinger_4'], x: 38, y: 43 },
  { id: 'gunslinger_7', title: '3圈神枪手地球', subTitle: '3-Turn GS Earth', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手地球三圈', difficulty: 4, unlockRequirements: ['gunslinger_6'], x: 28, y: 40 },
  { id: 'gunslinger_8', title: '1-2-3 神枪手地球', subTitle: '1-2-3 GS Earth', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手地球1到3递增', difficulty: 5, unlockRequirements: ['gunslinger_7'], x: 12, y: 38 },
  { id: 'gunslinger_9', title: '勺式神枪手转剑', subTitle: 'Scoop GS Turn', constellationId: 'gunslinger', category: 'gunslinger', description: '勺式握法神枪手转剑', difficulty: 3, unlockRequirements: ['gunslinger_4'], x: 47, y: 49 },
  { id: 'gunslinger_10', title: '神枪手天中杀', subTitle: 'Gunslinger Heaven Spike', constellationId: 'gunslinger', category: 'gunslinger', description: '神枪手版天中杀', difficulty: 4, unlockRequirements: ['gunslinger_9'], x: 57, y: 55 },

  // ========== JUNGLE (小丑) ==========
  { id: 'juggle_1', title: '小丑止剑', subTitle: 'Juggle Spike', constellationId: 'juggle', category: 'juggle', description: '小丑系列核心——基础止剑', difficulty: 2, unlockRequirements: [], x: 50, y: 51 },
  { id: 'juggle_2', title: '小丑止剑3', subTitle: 'Juggle Spike 3', constellationId: 'juggle', category: 'juggle', description: '小丑止剑三圈', difficulty: 3, unlockRequirements: ['juggle_1'], x: 34, y: 46 },
  { id: 'juggle_3', title: '小丑止剑5', subTitle: 'Juggle Spike 5', constellationId: 'juggle', category: 'juggle', description: '小丑止剑五圈', difficulty: 3, unlockRequirements: ['juggle_2'], x: 40, y: 39 },
  { id: 'juggle_4', title: '小丑止剑7', subTitle: 'Juggle Spike 7', constellationId: 'juggle', category: 'juggle', description: '小丑止剑七圈', difficulty: 4, unlockRequirements: ['juggle_3'], x: 47, y: 31 },
  { id: 'juggle_5', title: '小丑止剑10', subTitle: 'Juggle Spike 10', constellationId: 'juggle', category: 'juggle', description: '小丑止剑十圈——极致', difficulty: 5, unlockRequirements: ['juggle_4'], x: 41, y: 22 },
  { id: 'juggle_6', title: '小丑大皿', subTitle: 'Juggle Big Cup', constellationId: 'juggle', category: 'juggle', description: '小丑风格大皿', difficulty: 2, unlockRequirements: ['juggle_1'], x: 44, y: 64 },
  { id: 'juggle_7', title: '小丑抛剑', subTitle: 'Juggle Toss', constellationId: 'juggle', category: 'juggle', description: '小丑式抛剑', difficulty: 3, unlockRequirements: ['juggle_6'], x: 50, y: 73 },
  { id: 'juggle_8', title: '小丑天中杀', subTitle: 'Juggle Heaven Spike', constellationId: 'juggle', category: 'juggle', description: '小丑版天中杀', difficulty: 3, unlockRequirements: ['juggle_1'], x: 61, y: 60 },
  { id: 'juggle_9', title: '小丑大鸟', subTitle: 'Juggle Big Bird', constellationId: 'juggle', category: 'juggle', description: '小丑风格大鸟平衡', difficulty: 3, unlockRequirements: ['juggle_8'], x: 61, y: 43 },
  { id: 'juggle_10', title: '小丑止剑一周', subTitle: 'Juggle Spike 1 Turn', constellationId: 'juggle', category: 'juggle', description: '小丑止剑加一周回转', difficulty: 4, unlockRequirements: ['juggle_9'], x: 61, y: 32 },

  // ========== KENFLIP (离转系) ==========
  { id: 'kenflip_1', title: '离转地球', subTitle: 'Kenflip Earth', constellationId: 'kenflip', category: 'kenflip', description: '离转系核心——剑体翻转接地球', difficulty: 3, unlockRequirements: [], x: 42, y: 28 },
  { id: 'kenflip_2', title: '2离转地球', subTitle: '2 Kenflip Earth', constellationId: 'kenflip', category: 'kenflip', description: '双离转地球', difficulty: 3, unlockRequirements: ['kenflip_1'], x: 27, y: 42 },
  { id: 'kenflip_3', title: '3离转地球', subTitle: '3 Kenflip Earth', constellationId: 'kenflip', category: 'kenflip', description: '三离转地球', difficulty: 4, unlockRequirements: ['kenflip_2'], x: 33, y: 63 },
  { id: 'kenflip_4', title: '离转地球1-2-3', subTitle: 'Kenflip Earth 1-2-3', constellationId: 'kenflip', category: 'kenflip', description: '离转地球1到3递增连招', difficulty: 5, unlockRequirements: ['kenflip_3'], x: 48, y: 72 },
  { id: 'kenflip_5', title: '离转止剑', subTitle: 'Kenflip Spike', constellationId: 'kenflip', category: 'kenflip', description: '离转后止剑', difficulty: 3, unlockRequirements: ['kenflip_1'], x: 55, y: 39 },
  { id: 'kenflip_6', title: '离转大皿', subTitle: 'Kenflip Big Cup', constellationId: 'kenflip', category: 'kenflip', description: '离转系高难度变体', difficulty: 4, unlockRequirements: ['kenflip_5'], x: 50, y: 50 },
  { id: 'kenflip_7', title: '反离转地球', subTitle: 'Reverse Kenflip Earth', constellationId: 'kenflip', category: 'kenflip', description: '反向离转地球', difficulty: 3, unlockRequirements: ['kenflip_1'], x: 67, y: 32 },
  { id: 'kenflip_8', title: '正反离转地球', subTitle: 'Forward-Reverse Kenflip Earth', constellationId: 'kenflip', category: 'kenflip', description: '正反双向离转地球', difficulty: 4, unlockRequirements: ['kenflip_7'], x: 75, y: 46 },
  { id: 'kenflip_9', title: '离转小丑止剑', subTitle: 'Kenflip Joker Spike', constellationId: 'kenflip', category: 'kenflip', description: '离转小丑止剑组合', difficulty: 4, unlockRequirements: ['kenflip_8'], x: 71, y: 60 },
  { id: 'kenflip_10', title: '离转小丑-离转小丑止剑', subTitle: 'KF Joker- KF Joker Spike', constellationId: 'kenflip', category: 'kenflip', description: '双重离转小丑终极连招', difficulty: 5, unlockRequirements: ['kenflip_9'], x: 64, y: 67 },

  // ========== LIGHTHOUSE (灯台系) ==========
  { id: 'lighthouse_1', title: '灯台', subTitle: 'Lighthouse', constellationId: 'lighthouse', category: 'lighthouse', description: '灯台系核心——球在剑柄上的平衡', difficulty: 3, unlockRequirements: [], x: 75, y: 71 },
  { id: 'lighthouse_2', title: '1回转灯台', subTitle: '1-Turn Lighthouse', constellationId: 'lighthouse', category: 'lighthouse', description: '灯台加一回转', difficulty: 3, unlockRequirements: ['lighthouse_1'], x: 22, y: 71 },
  { id: 'lighthouse_3', title: '灯上1回转', subTitle: 'Lighthouse 1-Turn', constellationId: 'lighthouse', category: 'lighthouse', description: '灯台上方一回转', difficulty: 4, unlockRequirements: ['lighthouse_2'], x: 47, y: 65 },
  { id: 'lighthouse_4', title: '1回灯-灯上1回', subTitle: '1-Turn LH-Up', constellationId: 'lighthouse', category: 'lighthouse', description: '一回转灯台接灯上一回转', difficulty: 4, unlockRequirements: ['lighthouse_3'], x: 45, y: 50 },
  { id: 'lighthouse_5', title: '灯台大乱', subTitle: 'Lighthouse Chaos', constellationId: 'lighthouse', category: 'lighthouse', description: '灯台乱序组合', difficulty: 5, unlockRequirements: ['lighthouse_3'], x: 56, y: 56 },
  { id: 'lighthouse_6', title: '2回转灯台', subTitle: '2-Turn Lighthouse', constellationId: 'lighthouse', category: 'lighthouse', description: '灯台双回转', difficulty: 4, unlockRequirements: ['lighthouse_4'], x: 53, y: 43 },
  { id: 'lighthouse_7', title: '倒奶灯台', subTitle: 'Falling Milk LH', constellationId: 'lighthouse', category: 'lighthouse', description: '倒奶式灯台——优雅的失衡之美', difficulty: 3, unlockRequirements: ['lighthouse_6'], x: 50, y: 34 },
  { id: 'lighthouse_8', title: 'Tap灯台', subTitle: 'Tap Lighthouse', constellationId: 'lighthouse', category: 'lighthouse', description: 'Tap动作衔接灯台', difficulty: 4, unlockRequirements: ['lighthouse_7'], x: 50, y: 17 },
  { id: 'lighthouse_9', title: '幽灵灯台', subTitle: 'Ghost Lighthouse', constellationId: 'lighthouse', category: 'lighthouse', description: '如幽灵般飘忽的灯台变体', difficulty: 4, unlockRequirements: ['lighthouse_7'], x: 39, y: 28 },
  { id: 'lighthouse_10', title: '小丑灯台', subTitle: 'Juggle Lighthouse', constellationId: 'lighthouse', category: 'lighthouse', description: '小丑风格的灯台', difficulty: 4, unlockRequirements: ['lighthouse_7'], x: 61, y: 28 },

  // ========== STILT (竹马战斧) ==========
  { id: 'stilt_1', title: '战斧', subTitle: 'Axe', constellationId: 'stilt', category: 'stilt', description: '战斧起手——力量与角度的结合', difficulty: 3, unlockRequirements: [], x: 27, y: 61 },
  { id: 'stilt_2', title: '反战斧', subTitle: 'Reverse Axe', constellationId: 'stilt', category: 'stilt', description: '反向战斧，角度反转', difficulty: 3, unlockRequirements: ['stilt_1'], x: 21, y: 49 },
  { id: 'stilt_3', title: '斧上1回转', subTitle: 'Axe 1-Turn', constellationId: 'stilt', category: 'stilt', description: '战斧加一回转', difficulty: 4, unlockRequirements: ['stilt_1'], x: 27, y: 41 },
  { id: 'stilt_4', title: '竹马', subTitle: 'Stilt', constellationId: 'stilt', category: 'stilt', description: '竹马基础——剑柄上的稳定', difficulty: 3, unlockRequirements: [], x: 50, y: 77 },
  { id: 'stilt_5', title: '反竹马', subTitle: 'Reverse Stilt', constellationId: 'stilt', category: 'stilt', description: '反向竹马', difficulty: 3, unlockRequirements: ['stilt_4'], x: 50, y: 55 },
  { id: 'stilt_6', title: '渡竹马', subTitle: 'Transfer Stilt', constellationId: 'stilt', category: 'stilt', description: '竹马间的转移动作', difficulty: 4, unlockRequirements: ['stilt_5'], x: 59, y: 58 },
  { id: 'stilt_7', title: '竹马1回转', subTitle: 'Stilt 1-Turn', constellationId: 'stilt', category: 'stilt', description: '竹马加一回转', difficulty: 4, unlockRequirements: ['stilt_6', 'stilt_4'], x: 59, y: 45 },
  { id: 'stilt_8', title: '竹马1.5', subTitle: 'Stilt 1.5', constellationId: 'stilt', category: 'stilt', description: '竹马1.5圈旋转', difficulty: 4, unlockRequirements: ['stilt_7'], x: 64, y: 34 },
  { id: 'stilt_9', title: '钩子', subTitle: 'Hook', constellationId: 'stilt', category: 'stilt', description: '钩子——竹马系高难分支', difficulty: 5, unlockRequirements: ['stilt_8'], x: 70, y: 25 },
  { id: 'stilt_10', title: '竹马2回转', subTitle: 'Stilt 2-Turn', constellationId: 'stilt', category: 'stilt', description: '竹马双回转', difficulty: 5, unlockRequirements: ['stilt_8'], x: 59, y: 20 },

  // ========== STRING (线技) ==========
  { id: 'string_1', title: '提线止剑', subTitle: 'String Spike', constellationId: 'string', category: 'string', description: '线技核心——提线后止剑', difficulty: 2, unlockRequirements: [], x: 50, y: 76 },
  { id: 'string_2', title: '飞行V', subTitle: 'Flying V', constellationId: 'string', category: 'string', description: 'V字形绳技飞行', difficulty: 3, unlockRequirements: ['string_1'], x: 51, y: 65 },
  { id: 'string_3', title: '手铐', subTitle: 'Handcuffs', constellationId: 'string', category: 'string', description: '手铐——绳索缠绕技', difficulty: 3, unlockRequirements: ['string_2'], x: 62, y: 57 },
  { id: 'string_4', title: '弹弓', subTitle: 'Slingshot', constellationId: 'string', category: 'string', description: '弹弓式绳技发射', difficulty: 3, unlockRequirements: ['string_3'], x: 38, y: 53 },
  { id: 'string_5', title: '螺旋', subTitle: 'Spiral', constellationId: 'string', category: 'string', description: '绳索螺旋旋转', difficulty: 3, unlockRequirements: ['string_4'], x: 48, y: 51 },
  { id: 'string_6', title: '蝴蝶', subTitle: 'Butterfly', constellationId: 'string', category: 'string', description: '蝴蝶——绳技中的优雅翻转', difficulty: 4, unlockRequirements: ['string_5'], x: 59, y: 43 },
  { id: 'string_7', title: '扇风机', subTitle: 'Fan', constellationId: 'string', category: 'string', description: '扇风——快速绳技旋转', difficulty: 4, unlockRequirements: ['string_6'], x: 38, y: 38 },
  { id: 'string_8', title: '圆月快剑', subTitle: 'Full Moon Quick', constellationId: 'string', category: 'string', description: '圆月——快速的剑体回转', difficulty: 4, unlockRequirements: ['string_7'], x: 68, y: 37 },
  { id: 'string_9', title: '宇宙游泳', subTitle: 'Space Swing', constellationId: 'string', category: 'string', description: '宇宙级绳间游泳', difficulty: 4, unlockRequirements: ['string_8'], x: 50, y: 31 },
  { id: 'string_10', title: '2圈宇宙游泳', subTitle: '2-Turn Space Swing', constellationId: 'string', category: 'string', description: '双圈宇宙游泳——终极线技', difficulty: 5, unlockRequirements: ['string_9'], x: 31, y: 27 },

  // ========== TAP (快手) ==========
  { id: 'tap_1', title: '止剑快手', subTitle: 'Spike Quick', constellationId: 'tap', category: 'tap', description: '快手系——快速止剑', difficulty: 2, unlockRequirements: [], x: 39, y: 72 },
  { id: 'tap_2', title: '跳剑快手', subTitle: 'Jump Quick', constellationId: 'tap', category: 'tap', description: '快速跳剑', difficulty: 3, unlockRequirements: ['tap_1'], x: 51, y: 62 },
  { id: 'tap_3', title: '天中杀快手', subTitle: 'Heaven Spike Quick', constellationId: 'tap', category: 'tap', description: '快速天中杀', difficulty: 3, unlockRequirements: ['tap_2'], x: 59, y: 52 },
  { id: 'tap_4', title: '玉中杀快手', subTitle: 'Ball Spike Quick', constellationId: 'tap', category: 'tap', description: '快速玉中杀', difficulty: 4, unlockRequirements: ['tap_3'], x: 70, y: 42 },
  { id: 'tap_5', title: '1 Tap', subTitle: '1 Tap', constellationId: 'tap', category: 'tap', description: '单次Tap——快手基础', difficulty: 2, unlockRequirements: [], x: 27, y: 62 },
  { id: 'tap_6', title: '2 Tap', subTitle: '2 Tap', constellationId: 'tap', category: 'tap', description: '双Tap——节奏加快', difficulty: 3, unlockRequirements: ['tap_5'], x: 41, y: 54 },
  { id: 'tap_7', title: '3 Tap', subTitle: '3 Tap', constellationId: 'tap', category: 'tap', description: '三Tap——连击成型', difficulty: 3, unlockRequirements: ['tap_6'], x: 49, y: 47 },
  { id: 'tap_8', title: '4 Tap', subTitle: '4 Tap', constellationId: 'tap', category: 'tap', description: '四Tap——终极连击', difficulty: 4, unlockRequirements: ['tap_7'], x: 69, y: 28 },
  { id: 'tap_9', title: 'Insta跳剑', subTitle: 'Insta Jump', constellationId: 'tap', category: 'tap', description: '即时跳剑——快手招牌', difficulty: 3, unlockRequirements: [], x: 30, y: 46 },
  { id: 'tap_10', title: 'Insta灯台', subTitle: 'Insta Lighthouse', constellationId: 'tap', category: 'tap', description: '即时灯台——快手接灯台', difficulty: 4, unlockRequirements: ['tap_9'], x: 50, y: 33 },
];

export const WOODS: WoodMaterial[] = [
  { id: 'beech', name: 'Beech', chineseName: '山毛榉木', description: '经典入门材质，重量适中', weight: '中', sound: '清脆', colorHex: '#D7C39C' },
  { id: 'maple', name: 'Maple', chineseName: '硬枫木', description: '硬度高，适合进阶玩家', weight: '重', sound: '明亮', colorHex: '#ECE1C7' },
  { id: 'purpleheart', name: 'Purpleheart', chineseName: '紫罗兰木', description: '高密度硬木，深紫色泽', weight: '极重', sound: '深沉', colorHex: '#64325C' },
  { id: 'zebrawood', name: 'Zebrawood', chineseName: '胡桃斑马木', description: '纹理独特，手感温润', weight: '中重', sound: '温润', colorHex: '#8C6C52' },
];

export const PAINTS: PaintFinish[] = [
  { id: 'sticky', name: 'Sticky Clear', chineseName: '超黏聚合物漆', description: '极强阻尼，适合高难度控球', tackiness: '5/5', colorHex: '#00F3FF' },
  { id: 'rubber', name: 'Silk Rubber', chineseName: '星系丝绒橡胶漆', description: '温润阻尼，适合流畅连招', tackiness: '4/5', colorHex: '#BD00FF' },
  { id: 'raw', name: 'Raw Wood', chineseName: '原木裸漆', description: '最硬核的自然手感', tackiness: '2/5', colorHex: '#F0E6D2' },
];
